name: 'PR labels'
description: |
  Extract labels from the PR that this build belongs to and make them 
  available to other actions.
author: joerick
outputs:
  labels:
    description: |
      The labels on this PR. A string containing tag identifiers surrounded
      with spaces for easy use with `contains`.
  labels-object:
    description: |
      The labels on this PR. A dictionary containing `true` where a label
      exists
runs:
  using: 'node12'
  main: 'dist/index.js'
